# Generated by Django 2.2.5 on 2019-09-03 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entrance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrance', models.CharField(max_length=32)),
                ('entrance_url', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('switch_key', models.CharField(max_length=128)),
                ('switch_value', models.BooleanField(default=False, verbose_name='Status')),
            ],
        ),
    ]
