"""
Django settings for Thunneycomb project.

Generated by 'django-admin startproject' using Django 2.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
from Thunneycomb.app_settings.logging_settings import THUNNEYCOMB_LOGGING
from Thunneycomb.app_settings.platycodon_settings import *
from Thunneycomb.app_settings.sso_settings import *
from Thunneycomb.app_settings.wiki_settings import WIKI_APPS, SITE_ID
from Thunneycomb.env_check import get_env

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '#u2tp7$%fgos$1v^$pkpocb117nxmcc+bem9uenfif%x$x-rp3'

ADMIN_SITE_HEADER = "Thunneycomb Admin"

# SECURITY WARNING: don't run with debug turned on in production!
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

CURRENT_ENV = get_env()
print(CURRENT_ENV)
LOGGING = THUNNEYCOMB_LOGGING
ALLOWED_HOSTS = []

# Database
if 'product' == CURRENT_ENV:
    DEBUG = False
    from .db_settings.mysql_db import MYSQL_DB
    DATABASES = MYSQL_DB
    ALLOWED_HOSTS = ['*']
elif 'macos' == CURRENT_ENV:
    DEBUG = True
    from .db_settings.postgre_db import POSTGRESQL_DB
    DATABASES = POSTGRESQL_DB
else:
    DEBUG = True
    user_path = os.getenv('HOME')
    db_path = os.path.join(user_path, 'webapp/debug')
    db_file = "db.sqlite3"
    if not os.path.exists(db_path):
        os.makedirs(db_path)
    print("debug db {}".format(os.path.join(db_path, db_file)))

    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.path.join(db_path, db_file),
        }
    }



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'home'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.locale.LocaleMiddleware'
]

ROOT_URLCONF = 'Thunneycomb.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'sekizai.context_processors.sekizai',  # Django-wiki Dep
            ],
        },
    },
]

WSGI_APPLICATION = 'Thunneycomb.wsgi.application'


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/
# STATIC_URL = '/static/'

MEDIA_URL = "/media/"
STATIC_URL = '/static/'

if DEBUG:
    MEDIA_ROOT = os.path.join(BASE_DIR, "media")
    STATIC_ROOT = os.path.join(BASE_DIR, "static")
else:
    MEDIA_ROOT = "/var/www/thunneycomb/media/"
    STATIC_ROOT = "/var/www/thunneycomb/static/"


LOGIN_REDIRECT_URL = '/'
ADMIN_SITE_HEADER = "Thunneycomb Admin"


# APPS INSTALLED_APPS

INSTALLED_APPS += WIKI_APPS
INSTALLED_APPS += PLATYCODON_APPS
INSTALLED_APPS += SSO_APPS

