#! /usr/bin/env python
# -*- coding: utf-8 -*-
"""
Django settings for thunneycomb project.

Generated by 'django-admin startproject' using Django 1.9.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os

from thunneycomb.appsetting.logging_settings import THUNNEYCOMB_LOGGING, NOW_STRFTIME
from thunneycomb.appsetting.pet_api_settings import PET_APPS
from .env_check import get_env
from .appsetting.wiki_settings import *
from .appsetting.rest_settings import *
from .appsetting.platycodon_settings import *
from .appsetting.thunder_tokenbackend_settings import *
from .appsetting.thunder_customer_settings import *
from .appsetting.send_submail_sms_settings import *
from .db_setting.mysql_db import MYSQL_DB

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'kv%nxx(07o53+&__xvse93+v_!*(o4kcds$#ifyg0_*7omak_c'

# SECURITY WARNING: don't run with debug turned on in production!
CURRENT_ENV = get_env()
print(CURRENT_ENV)
LOGGING = THUNNEYCOMB_LOGGING

if 'product' == CURRENT_ENV:
    DEBUG = False
    DATABASES = MYSQL_DB
else:
    DEBUG = True
    user_path = os.getenv('HOME')
    db_path = os.path.join(user_path, 'webapp/debug/db.sqlite3')
    print("debug db {}".format(db_path))

    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': db_path,
        }
    }

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'home'
]

MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]

ROOT_URLCONF = 'thunneycomb.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.template.context_processors.i18n',
                'django.template.context_processors.media',
                'django.template.context_processors.static',
                'django.template.context_processors.tz',
                'django.contrib.messages.context_processors.messages',
                "sekizai.context_processors.sekizai",
            ],
        },
    },
]

WSGI_APPLICATION = 'thunneycomb.wsgi.application'

SITE_ID = 1

# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'zh_cn'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/
# MEDIA_ROOT = "/var/www/thunneycomb/media"
if DEBUG is False:
    MEDIA_ROOT = "/var/www/thunneycomb/media/"
    STATIC_ROOT = "/var/www/thunneycomb/static/"
else:
    MEDIA_ROOT = os.path.join(BASE_DIR, "media")
    STATIC_ROOT = os.path.join(BASE_DIR, "static")

LOGIN_URL = "/account/login/"
MEDIA_URL = "/media/"
STATIC_URL = '/static/'

LOGIN_REDIRECT_URL = '/'
ADMIN_SITE_HEADER = "Thunneycomb Admin"

INSTALLED_APPS += WIKI_APPS
INSTALLED_APPS += REST_APPS
INSTALLED_APPS += PLATYCODON_APPS
INSTALLED_APPS += PET_APPS
INSTALLED_APPS += THUNDER_TOKEN
INSTALLED_APPS += THUNDER_CUSTOMER

